/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '#1B4FCC',
          'primary-hover': '#1640B3',
          'primary-light': '#E8EEFB',
          secondary: '#F5A623',
          'secondary-hover': '#DC941F',
          'secondary-light': '#FEF5E7',
          accent: '#00C896',
          'accent-hover': '#00B387',
          'accent-light': '#E6F9F4',
          danger: '#E53535',
          'danger-hover': '#CC2E2E',
          'danger-light': '#FDEAEA',
          warning: '#F5A623',
          'warning-hover': '#DC941F',
          'warning-light': '#FEF5E7',
        },
        surface: {
          base: '#F7F8FC',
          card: '#FFFFFF',
          subtle: '#EEF1FA',
          inverse: '#0D1B3E',
        },
        border: {
          DEFAULT: '#E2E8F0',
          subtle: '#F1F5F9',
          strong: '#CBD5E1',
        },
        text: {
          primary: '#0D1B3E',
          secondary: '#4A5568',
          muted: '#A0AEC0',
          inverse: '#FFFFFF',
          accent: '#1B4FCC',
        },
        indigo: {
          100: '#E0E7FF',
          200: '#C7D2FE',
          300: '#A5B4FC',
          400: '#818CF8',
          500: '#6366F1',
          600: '#4F46E5',
          700: '#4338CA',
          800: '#3730A3',
          900: '#312E81',
        },
      },
      fontFamily: {
        display: ['Sora', 'sans-serif'],
        body: ['DM Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['DM Sans', 'sans-serif'],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(13, 27, 62, 0.06), 0 4px 16px rgba(13, 27, 62, 0.08)',
        elevated: '0 8px 32px rgba(13, 27, 62, 0.12), 0 2px 8px rgba(13, 27, 62, 0.08)',
        brand: '0 4px 24px rgba(27, 79, 204, 0.20)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
      },
      zIndex: {
        dropdown: '1000',
        sticky: '1020',
        fixed: '1030',
        'modal-backdrop': '1040',
        modal: '1050',
        popover: '1060',
        tooltip: '1070',
      },
      scale: {
        '98': '.98',
      },
      animation: {
        'shimmer': 'shimmer 1.5s infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [],
}
